export * as schema from './schema.js'
export {
  registry,
  registrations,
  currentRegistration,
  statsSummary,
  statsByYear,
  statsByRegion,
  statsByRegionYear,
  statsByBody,
  statsByKind,
  statsByColor,
  statsByFuel,
  statsByBrand,
  statsByBrandYear,
  statsByModel,
  statsByOrigin,
  ingestedResources,
  euroncapRatings,
  jncapRatings,
  cncapRatings,
  kncapRatings,
  infocarVersions,
  iihsRatings,
  fuelEconomy,
  statsFuel,
  statsSafety,
  type RegistrationRow,
  type RegistrationInsert,
  type IngestedResourceRow,
  type EuroncapRatingRow,
  type EuroncapRatingInsert,
  type JncapRatingRow,
  type JncapRatingInsert,
  type CncapRatingRow,
  type CncapRatingInsert,
  type KncapRatingRow,
  type KncapRatingInsert,
  type InfocarVersionRow,
  type InfocarVersionInsert,
  type IihsRatingRow,
  type IihsRatingInsert,
  type FuelEconomyRow,
  type FuelEconomyInsert,
  type StatsFuelInsert,
  type StatsSafetyInsert
} from './schema.js'
export {
  createDb,
  resolveDatabaseUrl,
  refreshCurrentRegistration,
  refreshStats,
  LOCAL_DATABASE_URL,
  type Db
} from './client.js'
export { runMigrations } from './migrate.js'
