export * as schema from './schema.js'
export {
  registry,
  registrations,
  currentRegistration,
  statsSummary,
  statsByYear,
  statsByRegion,
  statsByRegionYear,
  statsByBody,
  statsByKind,
  statsByColor,
  statsByFuel,
  statsByBrand,
  statsByBrandYear,
  statsByModel,
  statsByOrigin,
  ingestedResources,
  euroncapRatings,
  jncapRatings,
  cncapRatings,
  kncapRatings,
  infocarVersions,
  carVideos,
  youtubeVideos,
  youtubeModelRuns,
  ownerPosts,
  carModels3d,
  carModels360,
  winner360,
  siteVideos,
  topgearReviews,
  wikiImage,
  pressReviews,
  newsItems,
  socialPosts,
  missedLookups,
  app,
  users,
  authIdentities,
  sessions,
  userFeatures,
  userSavedEntries,
  userSettings,
  usageEvents,
  type UserRow,
  iihsRatings,
  fuelEconomy,
  vdbModels,
  rdwSpecs,
  rdwRecalls,
  rdwRecallModels,
  type RdwRecallRow,
  type RdwRecallInsert,
  type RdwRecallModelInsert,
  statsFuel,
  statsWeight,
  type StatsWeightInsert,
  statsVdb,
  statsSafety,
  type RegistrationRow,
  type RegistrationInsert,
  type IngestedResourceRow,
  type EuroncapRatingRow,
  type EuroncapRatingInsert,
  type JncapRatingRow,
  type JncapRatingInsert,
  type CncapRatingRow,
  type CncapRatingInsert,
  type KncapRatingRow,
  type KncapRatingInsert,
  type InfocarVersionRow,
  type InfocarVersionInsert,
  type CarVideoRow,
  type CarVideoInsert,
  type OwnerPostRow,
  type OwnerPostInsert,
  type CarModel3dRow,
  type CarModel3dInsert,
  type CarModel360Row,
  type CarModel360Insert,
  type Winner360Row,
  type Winner360Insert,
  type SiteVideoRow,
  type SiteVideoInsert,
  type TopgearReviewRow,
  type TopgearReviewInsert,
  type PressReviewRow,
  type PressReviewInsert,
  type NewsItemRow,
  type NewsItemInsert,
  type SocialPostRow,
  type SocialPostInsert,
  type PressLang,
  type PressLangEntry,
  type IihsRatingRow,
  type IihsRatingInsert,
  type FuelEconomyRow,
  type FuelEconomyInsert,
  type VdbModelRow,
  type RdwSpecsRow,
  type RdwSpecsInsert,
  type RdwFuelPrices,
  type RdwTally,
  type VdbModelInsert,
  type StatsFuelInsert,
  type StatsVdbInsert,
  type StatsSafetyInsert,
  type WikiImageRow,
  type WikiImageInsert,
  type YoutubeVideoRow,
  type YoutubeVideoInsert,
  type YoutubeModelRunRow,
  type YoutubeModelRunInsert
} from './schema.js'
export {
  createDb,
  resolveDatabaseUrl,
  refreshCurrentRegistration,
  refreshStats,
  LOCAL_DATABASE_URL,
  type Db
} from './client.js'
export { runMigrations } from './migrate.js'
export { findWikiImage, upsertWikiImages } from './wikiImage.js'
