/** NHTSA variable name → i18n key suffix (`vin.info.<key>`) of its plain-language explanation. */
export const FIELD_INFO: Readonly<Record<string, string>> = {
  'Vehicle Descriptor': 'descriptor',
  'Manufacturer Name': 'manufacturer',
  Series: 'series',
  Series2: 'series',
  Trim: 'trim',
  'Vehicle Type': 'vehicleType',
  'Body Class': 'bodyClass',
  Doors: 'doors',
  'Drive Type': 'driveType',
  'Transmission Style': 'transmission',
  'Transmission Speeds': 'transmissionSpeeds',
  'Gross Vehicle Weight Rating From': 'gvwr',
  'Gross Vehicle Weight Rating To': 'gvwr',
  'Engine Number of Cylinders': 'cylinders',
  'Displacement (CC)': 'displacement',
  'Displacement (CI)': 'displacement',
  'Displacement (L)': 'displacement',
  'Engine Model': 'engineModel',
  'Engine Configuration': 'engineConfig',
  'Engine Brake (hp) From': 'horsepower',
  'Engine Brake (hp) To': 'horsepower',
  'Engine Power (kW)': 'kilowatts',
  'Fuel Type - Primary': 'fuelPrimary',
  'Fuel Type - Secondary': 'fuelSecondary',
  'Valve Train Design': 'valveTrain',
  Turbo: 'turbo',
  'Electrification Level': 'electrification',
  'Seat Belt Type': 'seatBelt',
  Pretensioner: 'pretensioner',
  'Tire Pressure Monitoring System (TPMS) Type': 'tpms',
  'Front Air Bag Locations': 'airbagFront',
  'Side Air Bag Locations': 'airbagSide',
  'Curtain Air Bag Locations': 'airbagCurtain',
  'Knee Air Bag Locations': 'airbagKnee',
  'Anti-lock Braking System (ABS)': 'abs',
  'Electronic Stability Control (ESC)': 'esc',
  'Traction Control': 'tc',
  'Forward Collision Warning (FCW)': 'fcw',
  'Dynamic Brake Support (DBS)': 'dbs',
  'Pedestrian Automatic Emergency Braking (PAEB)': 'aeb',
  'Adaptive Cruise Control (ACC)': 'acc',
  'Lane Departure Warning (LDW)': 'ldw',
  'Lane Keeping Assistance (LKA)': 'lka',
  'Blind Spot Warning (BSW)': 'bsw',
  'Rear Cross Traffic Alert (RCTA)': 'rcta',
  'Keyless Ignition': 'keyless',
  'Daytime Running Light (DRL)': 'drl'
}
