export { normalizePlate, denormalizePlate, isVin, classifyQuery, repairOcrPlate } from './plate.js'
export { REGIONS, REGION_NAMES, regionName, platePrefixesForRegion } from './regions.js'
export { VEHICLE_KINDS, resolveVehicleKind, sourceValueForKind, type VehicleKind } from './vehicleKind.js'
export {
  VEHICLE_COLORS,
  VEHICLE_COLOR_HEX,
  VEHICLE_COLOR_SHADOW_HEX,
  resolveVehicleColor,
  sourceValuesForColor,
  fallbackVehicleColor,
  isLightVehicleColor,
  type VehicleColor
} from './vehicleColor.js'
export { VEHICLE_FUELS, resolveFuelCategories, fuelKeyword, type VehicleFuel } from './vehicleFuel.js'
export { brandLogoUrl, brandSlug } from './brandLogo.js'
export { dealerUrl } from './dealerUrl.js'
export { wikiUrl, wikiDomain } from './wikiUrl.js'
export { makeKey, modelKey } from './vehicleKey.js'
export {
  registrationSchema,
  plateLookupResponseSchema,
  plateHistoryResponseSchema,
  vinDecodeResponseSchema,
  vinRegistrySchema,
  apiErrorSchema,
  plateCandidateSchema,
  plateRecognizeResponseSchema,
  vehiclePhotoSchema,
  vehiclePhotosResponseSchema,
  safetyRatingSchema,
  safetyRatingsResponseSchema,
  euroNcapRatingSchema,
  euroNcapRatingsResponseSchema,
  jncapTestScoreSchema,
  jncapRatingSchema,
  jncapRatingsResponseSchema,
  CNCAP_VEHICLE_CLASSES,
  cncapRatingSchema,
  cncapRatingsResponseSchema,
  kncapRatingSchema,
  kncapRatingsResponseSchema,
  iihsTestSchema,
  iihsRatingSchema,
  iihsRatingsResponseSchema,
  statsMetricsSchema,
  statsByYearRowSchema,
  statsByRegionRowSchema,
  statsByRegionYearRowSchema,
  statsByDimensionRowSchema,
  statsByModelRowSchema,
  statsResponseSchema,
  dataVersionResponseSchema,
  wikiImageAttributionSchema,
  wikiImageSchema,
  wikiInfoResponseSchema,
  brandSuggestionSchema,
  brandSuggestionsResponseSchema,
  modelSuggestionSchema,
  modelSuggestionsResponseSchema,
  searchResultRowSchema,
  searchResponseSchema,
  type Registration,
  type PlateLookupResponse,
  type PlateHistoryResponse,
  type VinDecodeResponse,
  type VinRegistry,
  type ApiError,
  type PlateCandidate,
  type PlateRecognizeResponse,
  type VehiclePhoto,
  type VehiclePhotosResponse,
  type SafetyRating,
  type SafetyRatingsResponse,
  type EuroNcapRating,
  type EuroNcapRatingsResponse,
  type JncapTestScore,
  type JncapRating,
  type JncapRatingsResponse,
  type CncapVehicleClass,
  type CncapRating,
  type CncapRatingsResponse,
  type KncapRating,
  type KncapRatingsResponse,
  type IihsTest,
  type IihsRating,
  type IihsRatingsResponse,
  type StatsMetrics,
  type StatsByYearRow,
  type StatsByRegionRow,
  type StatsByRegionYearRow,
  type StatsByDimensionRow,
  type StatsByModelRow,
  type StatsResponse,
  type DataVersionResponse,
  type WikiImageAttribution,
  type WikiImage,
  type WikiInfo,
  type BrandSuggestion,
  type BrandSuggestionsResponse,
  type ModelSuggestion,
  type ModelSuggestionsResponse,
  type SearchResultRow,
  type SearchResponse
} from './schemas.js'
