export { normalizePlate, denormalizePlate, isVin, classifyQuery, repairOcrPlate } from './plate.js'
export { REGIONS, regionName } from './regions.js'
export {
  registrationSchema,
  plateLookupResponseSchema,
  plateHistoryResponseSchema,
  vinDecodeResponseSchema,
  vinRegistrySchema,
  apiErrorSchema,
  plateCandidateSchema,
  plateRecognizeResponseSchema,
  vehiclePhotoSchema,
  vehiclePhotosResponseSchema,
  statsMetricsSchema,
  statsByYearRowSchema,
  statsByRegionRowSchema,
  statsByRegionYearRowSchema,
  statsByDimensionRowSchema,
  statsResponseSchema,
  type Registration,
  type PlateLookupResponse,
  type PlateHistoryResponse,
  type VinDecodeResponse,
  type VinRegistry,
  type ApiError,
  type PlateCandidate,
  type PlateRecognizeResponse,
  type VehiclePhoto,
  type VehiclePhotosResponse,
  type StatsMetrics,
  type StatsByYearRow,
  type StatsByRegionRow,
  type StatsByRegionYearRow,
  type StatsByDimensionRow,
  type StatsResponse
} from './schemas.js'
